
---
- name: install mariadb
  yum:
    name: mariadb105
    state: latest
- name: install mariadb server
  yum:
    name: mariadb105-server
    state: latest
- name: install php_mysql
  yum:
    name: php-mysqlnd
    state: latest
- name: start mariadb
  service:
    name: mariadb
    state: started
    
